name = "HPModel"
uuid = "e84a1301-674d-4f36-898b-c8a02436684f"
version = "0.1.0"
authors = ["Francesco Fadda <francesco.fadda.academic@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1.6.3"
CairoMakie = "0.15.8"
Combinatorics = "1.1.0"
GLMakie = "0.13.8"
LaTeXStrings = "1.4.0"
Profile = "1.11.0"
StaticArrays = "1.9.15"
julia = "1.12"
