name = "HPModel"
uuid = "e84a1301-674d-4f36-898b-c8a02436684f"
version = "0.1.0"
authors = ["Francesco Fadda <francesco.fadda.academic@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
BenchmarkTools = "1.6.3"
julia = "1.12"
